### ISSUE TITLE
Get "if: Symbol’s function definition is void: subseq" when running M-x gendoxy tag

### ISSUE THREAD

**Issue by jderoo** [mp81ss/gendoxy#1]
Experimenting with gendoxy for an embedded application written in C for a Cortex processor.  Using Gnu Emacs 26.3 on a Mac.  I put the point on the header of the function, do M-x gendoxy-tag, and get the error above.  Looked in gdendoxy.el and found only one place where subseq is used.  But I don't have a subseq command that I can find.  Is there a package dependency or do I need a different version or is it something else?  the gendoxy-tag worked for several other functions, but those were void return type and no parameter.  The definition of the function that gave the problem starts with

uint32 set_all_lights(uint8 intensity)
{
    uint32 status = 0;
...

Thanks,
John DeRoo

**Comment by mp81ss** [comment]
I cannot reproduce the problem, anyway I removed the _subseq_, should work on next version.
In the meantime, replace _subseq_ with _seq-subseq_

**Comment by mp81ss** [comment]
Fixed code

**Comment by jderoo** [comment]
Thanks - that works for me.
